/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;
import java.util.List;

public class App {
    public static void main(String[] args) {
        ShoppingCart cart = new ShoppingCart();
        Scanner scanner = new Scanner(System.in);
        int choice = -1;

        System.out.println("Welcome to the Shopping Cart Application!");

        while (choice != 4) {
            printMenu();
            try {
                System.out.print("Enter your choice: ");
                choice = Integer.parseInt(scanner.nextLine());

                switch (choice) {
                    case 1:
                        addItemToCart(cart, scanner);
                        break;
                    case 2:
                        deleteItemFromCart(cart, scanner);
                        break;
                    case 3:
                        printCartContents(cart);
                        break;
                    case 4:
                        System.out.println("Exiting the application. Thank you for shopping!");
                        break;
                    default:
                        System.out.println("Invalid choice. Please enter a number between 1 and 4.");
                }
            } catch (NumberFormatException e) {
                System.out.println("Invalid input. Please enter a number.");
            }
            System.out.println();
        }

        scanner.close();
    }

    private static void printMenu() {
        System.out.println("Please choose an option:");
        System.out.println("1. Add item to cart");
        System.out.println("2. Delete item from cart");
        System.out.println("3. View cart");
        System.out.println("4. Exit");
    }

    private static void addItemToCart(ShoppingCart cart, Scanner scanner) {
        System.out.print("Enter the item to add: ");
        String item = scanner.nextLine();
        cart.addItem(item);
        System.out.println(item + " added to the cart.");
    }

    private static void deleteItemFromCart(ShoppingCart cart, Scanner scanner) {
        if (cart.getItems().isEmpty()) {
            System.out.println("Your cart is empty. Nothing to delete.");
            return;
        }

        System.out.println("Items in your cart:");
        List<String> currentItems = cart.getItems();
        for (int i = 0; i < currentItems.size(); i++) {
            System.out.println((i + 1) + ". " + currentItems.get(i));
        }

        System.out.print("Enter the number of the item to delete: ");
        try {
            int itemNumber = Integer.parseInt(scanner.nextLine());
            if (itemNumber > 0 && itemNumber <= currentItems.size()) {
                String removedItem = cart.removeItem(itemNumber - 1);
                currentItems = cart.getItems();

                System.out.println(removedItem + " removed from the cart.");

            } else {
                System.out.println("Invalid item number.");
            }
        } catch (NumberFormatException e) {
            System.out.println("Invalid input. Please enter a number.");
        }
    }

    private static void printCartContents(ShoppingCart cart) {
        System.out.println("--- Your Shopping Cart ---");
        if (cart.getItems().isEmpty()) {
            System.out.println("Your cart is empty.");
        } else {
            for (int i = 0; i < cart.getItems().size(); i++) {
                System.out.println((i + 1) + ". " + cart.getItems().get(i));
            }
        }
        System.out.println("Is a book added? " + cart.isBookAdded());
        System.out.println("--------------------------");
    }
}
